spring:
  config:
    activate:
      on-profile: test

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:communiversetest;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;NON_KEYWORDS=user,like,post,comment
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  pattern.level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}][%X{operation:-},%X{model:-},%X{user:-}]"
  level:
    root: INFO
    org:
      hibernate: ERROR # set to TRACE to see query bound values

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml